### ISSUE TITLE
segmented-cilia

### ISSUE THREAD

**Issue by tischi** [platybrowser/platybrowser-backend#12]
@constantinpape could it be that the segmented-cilia default table does not exist?

**Comment by tischi** [comment]
@constantinpape or maybe the table is actually fine.
could there be an issue with this file? 
```
<SpimData version="0.2">
  <BasePath type="relative">.</BasePath>
  <SequenceDescription>
    <ViewSetups>
      <Attributes name="channel">
        <Channel>
          <id>1</id>
          <name>1</name>
        </Channel>
      </Attributes>
      <ViewSetup>
        <id>0</id>
        <name>channel 1</name>
        <size>27499 25916 11416</size>
        <voxelSize>
          <unit>micrometer</unit>
          <size>0.01 0.01 0.025</size>
        </voxelSize>
        <attributes>
          <channel>1</channel>
        </attributes>
      </ViewSetup>
    </ViewSetups>
    <Timepoints type="range">
      <first>0</first>
      <last>0</last>
    </Timepoints>
    <ImageLoader format="bdv.n5.s3">
      <Key>0.6.2/images/remote/sbem-6dpf-1-whole-segmented-cilia.n5</Key>
      <SigningRegion>us-west-2</SigningRegion>
      <ServiceEndpoint>https://s3.embl.de</ServiceEndpoint>
      <BucketName>platybrowser</BucketName>
    </ImageLoader>
  </SequenceDescription>
  <ViewRegistrations>
    <ViewRegistration setup="0" timepoint="0">
      <ViewTransform type="affine">
        <affine>0.01 0.0 0.0 0.0 0.0 0.01 0.0 0.0 0.0 0.0 0.025 0.0</affine>
      </ViewTransform>
    </ViewRegistration>
  </ViewRegistrations>
</SpimData>
```

**Comment by constantinpape** [comment]
I haven't uploaded the cilia segmentation to s3 yet, because it is also quite large / I need to check that I did everything correct with chunking. I will try to upload it tomorrow.
See also #7.

**Comment by constantinpape** [comment]
I added the cilia segmentation to s3 now, but somehow it behaves very weirdly.
I will check first if there is something wrong with the local file.

**Comment by constantinpape** [comment]
I think this is the int16 problem as well.

**Comment by tischi** [comment]
Does it work now?

**Comment by constantinpape** [comment]
There were no updates to the fiji plugin I could install, so I don't expect any changes ...

**Comment by tischi** [comment]
> There were no updates to the fiji plugin I could install, so I don't expect any changes ...

This is strange, I uploaded `bigdataviewer-core` with the fixes to Fiji yesterday night. 
Can you check which version number and age the file in your jars folder has?

**Comment by tischi** [comment]
...but I don't see them either (also not if I move around in bdv):

<img width="331" alt="image" src="https://user-images.githubusercontent.com/2157566/74380172-624aa800-4de9-11ea-833b-aafa4ef76eb7.png">

**Comment by constantinpape** [comment]
Now bdv-core got updated and virtual cells are working for me.
Still not seeing the cilia either, so the issue here might be unrelated to the empty chunk issue.

I will check the volume again tomorrow.

**Comment by constantinpape** [comment]
I checked the segmentation in python, and it seems to be correct.

**Comment by tischi** [comment]
If one zooms in they appear. 
It looks like they are only present in the highest level of the resolution pyramid.

<img width="525" alt="image" src="https://user-images.githubusercontent.com/2157566/74463412-19026300-4e92-11ea-8335-f421ae653602.png">

**Comment by constantinpape** [comment]
This was an issue in the n5 metadata. Fixed it.
