### ISSUE TITLE
Rename version 0.6.6 to 1.0.0

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/platybrowser-backend#17]
I would like to call what is currently version `0.6.6` `1.0.0` to indicate that this is the version at time of submission.
From my point all the data is added to this now, but we are still lacking a few things:
- Check that gene and virtual cell assignments are correct, @vzinche
- Check that the cell and nucleus morphology tables are correct and add the morphology clustering, @K-Meech 

Please let me know if any of this is done, but this is not very urgent.

**Comment by vzinche** [comment]
Gene and virtual cell assignments seem to be correct :+1:

**Comment by K-Meech** [comment]
The morphology tables look good! I'm re-running my code at the moment, so should have the clustering files soon

**Comment by constantinpape** [comment]
I think all tables are checked now and we have also added the cell morphology clustering.
@K-Meech @vzinche @tischi 
Unless you have any concerns (like running scripts that depend on the folder-name), I will rename to 1.0.0 tomorrow.

**Comment by K-Meech** [comment]
Fine with me! Although there will still be tables with the nearest neighbour results to add

**Comment by constantinpape** [comment]
> Although there will still be tables with the nearest neighbour results to add

It's fine if we add some more things to 1.0.0 later. I just didn't want to do this as long as there were too many moving parts. I still have some computations running which rely on the folder name, should be finished after lunch and I will rename then.

**Comment by constantinpape** [comment]
Done in 5862aeb
