### ISSUE TITLE
Confusing definition of a Segmentation image

### ISSUE THREAD

**Issue by tischi** [platybrowser/platybrowser-backend#20]
@constantinpape 

Right now, I am having this in my code (with `Segmentation` occurring twice):

```java

public class Metadata
{
        ...

	public enum Modality
	{
		Segmentation,
		FM,
		EM,
		XRay
	}

	public enum Type
	{
		Image,
		Segmentation,
		Mask,
	}
}
```

This has been growing like this for historical reasons. 
We should think about it and clean this up at some point.

**Comment by constantinpape** [comment]
Yes, `Segmentation` should not be part of `Modality`.

**Comment by tischi** [comment]
> Yes, Segmentation should not be part of Modality.

I think that solves it.
