### ISSUE TITLE
Bookmarks: color by column

### ISSUE THREAD

**Issue by tischi** [platybrowser/platybrowser-backend#22]
@vzinche @constantinpape @HernandoMV @K-Meech 

I think this is not yet entirely logical:

```
"sbem-6dpf-1-whole-segmented-cells": {
        "Tables": {
          "vc_assignments": [
            "expression_sum",
            "glasbey"
          ]
        }
```

There could be multiple additional tables, but there can be only one column based colouring scheme. Thus, I think the "expression_sum", "glasbey"  is not a property of "vc_assignments", but of "sbem-6dpf-1-whole-segmented-cells". 

I would propose to do it instead like this:

```java
"sbem-6dpf-1-whole-segmented-cells": {
        "Tables": [ "default", "vc_assignments" ],
        "ColorMap": "Glasbey",
        "MaxValue": 1000,
        "MinValue": 0,
        "ColorByColumn": "expression_sum"
        }
```

, where, if  "ColorByColumn" is missing, it defaults to `"ColorByColumn" : "label_id"`

An important point here is that I realised that `bookmarks.json` is **very similar** to `images.json`.
In fact, I am now trying to use the same code to parse both of them. To make this even more consistent, I would thus propose to make them even more similar, for example by introducing above changes. 

What do you think?

**Comment by constantinpape** [comment]
@tischi the changes you propose make a lot of sense, I will update the `bookmarks.json` tomorrow.

> where, if "ColorByColumn" is missing, it defaults to `"ColorByColumn" : "label_id"`

Just keep in mind that we need to support the case where no table is present as well.

> An important point here is that I realised that `bookmarks.json` is **very similar** to `images.json`.

That is very much intended :). And indeed what you propose makes it even more similar.

**Comment by tischi** [comment]
> Just keep in mind that we need to support the case where no table is present as well.

I think that's no problem, is it? Either `Tables` key is missing or list is empty. Both cases could be readily parsed.

> That is very much intended :). And indeed what you propose makes it even more similar.

Ok, great! Feel free to see whether you find more ways to make them even more similar. I think it would also improve your life on the writing side of those json files.

**Comment by constantinpape** [comment]
I have changed the bookmarks to the new table layout.

> I think that's no problem, is it? Either `Tables` key is missing or list is empty. Both cases could be readily parsed.

No, it is not a problem. Just wanted to make sure you are aware of that case.

> Ok, great! Feel free to see whether you find more ways to make them even more similar. I think it would also improve your life on the writing side of those json files.

I couldn't think of anything else for now.
