### ISSUE TITLE
Figure 6 Bookmarks

### ISSUE THREAD

**Issue by tischi** [platybrowser/platybrowser-backend#27]
Maybe these figure titles could be improved?

<img width="372" alt="image" src="https://user-images.githubusercontent.com/2157566/74591402-fb5f0600-5017-11ea-8f56-0679c11f37d4.png">

cc @HernandoMV

**Comment by vzinche** [comment]
You don't like the 6F one, or all of them? If all, what don't you like about the 6A and 6B?

**Comment by tischi** [comment]
1. 6A and 6B are the same, is that correct?
2. Could you spell out VC as Virtual Cells and still try to make it shorter? 😄

**Comment by vzinche** [comment]
1) Yes, basically they are the same, just with different genes. I don't really want to add the gene names, though, it might be too long
2) Yup, is it better [here](https://github.com/platybrowser/platybrowser-backend/pull/31/commits/ff025a89c62e315e6da47888a27952e8b42cc949)?
