### ISSUE TITLE
Views in bookmarks

### ISSUE THREAD

**Issue by tischi** [platybrowser/platybrowser-backend#35]
@HernandoMV @vzinche @constantinpape @K-Meech 

It turns out that the `View` AffineTransform in the `Bookmarks.json` only looks correct if the BigDataViewer window has the exact same size (in pixels) as for it had for the person recording this `View`. Maybe we could at least make it such that the `Views` look good if one keeps the default size of the BigDataViewer window when the application opens. 

You can try this: resize the Bdv Window and view a Bookmark => the View may not fit.

Opinions?

**Comment by vzinche** [comment]
For me it's fully sufficient if it centers the bookmarks by Position. If the view doesn't fit, I guess it's pretty intuitive for a user to enlarge the BDV window

**Comment by constantinpape** [comment]
I agree with @vzinche. As long as the view is centered on more or less the right position this is fine and users can enlarge the window and will probably move and zoom around anyways.

**Comment by K-Meech** [comment]
Sounds good to me too! Happy to resize / move the window a bit as long as the general location is correct.

**Comment by tischi** [comment]
ok. let's leave it like this for now.
