### ISSUE TITLE
Update all gene names

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/platybrowser-backend#4]
We need to match gene names with the new prospr file names in:
-  'gene_names' dataset of [auxiliary gene file](https://github.com/platybrowser/platybrowser-backend/blob/master/data/0.6.5/misc/prospr-6dpf-1-whole_meds_all_genes.xml)
- [Prospr table](https://github.com/platybrowser/platybrowser-backend/blob/master/data/0.6.0/tables/prospr-6dpf-1-whole-virtual-cells/profile_clust_curated.csv)

I tried for the dataset already, but 2 gene names do not match up, see https://github.com/platybrowser/platybrowser-backend/blob/new-update-mechanism/misc/fixup.py#L71-L102.

**Comment by vzinche** [comment]
https://github.com/platybrowser/platybrowser-backend/blob/a96507900c5948ab1a9a34be74bc3b21cbf33b65/misc/new_name_lut.json#L30
https://github.com/platybrowser/platybrowser-backend/blob/a96507900c5948ab1a9a34be74bc3b21cbf33b65/misc/new_name_lut.json#L37

These two non-matching names actually originate from the renaming. So probably a cleaner way would be: if the gene_name starts with ENR or NOV, find the corresponding ENR or NOV in json

**Comment by constantinpape** [comment]
@vzinche 
I fixed the gene names in the all meds hdf5 file in a1c4056.

**Comment by constantinpape** [comment]
I have added the new vc profile table @vzinche made and I rerun computation for the vc assignment table. As far as I can see, all gene names are up-to-date now.
