### ISSUE TITLE
Virtual cell files are missing segmented tag?

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/platybrowser-backend#5]
The virtual cells should behave like segmentations in the platy-browser, so do they need the `segmented`tag in the filename?
Haven't checked how they are currently displayed in the browser.

**Comment by tischi** [comment]
also something to discuss along the `mask` issue on Monday morning.

For example, we have to distinguish between segmentation images where the segments should be _interactive_ in terms of being selectable by mouse clicks, or whether this is not the case. 

In general, I am leaning towards adding more`'Modality` information to `images.json`.

**Comment by constantinpape** [comment]
> In general, I am leaning towards adding more`'Modality` information to `images.json`.

Sounds good, let's discuss tomorrow.

**Comment by constantinpape** [comment]
Fixed by new `Modality` field, see #10.

**Comment by vzinche** [comment]
The sbem segmentation tissue has the same problem as the virtual cells. 
Even funnier, the colors are visible only when you scroll: 

![tissue_segm](https://user-images.githubusercontent.com/32451366/74246485-e1a28380-4ce4-11ea-910f-6fd0079d8968.gif)

**Comment by constantinpape** [comment]
> The sbem segmentation tissue has the same problem as the virtual cells.
> Even funnier, the colors are visible only when you scroll:

@tischer this really looks like the missing chunks issue.
The tissue also has dtype int16, so I am pretty sure you did not push the changes we made to this yesterday.

**Comment by tischi** [comment]
does it work now after you update Fiji?

**Comment by vzinche** [comment]
No, it even throws an exception when I try to load the vcs
![Screenshot from 2020-02-12 09-33-50](https://user-images.githubusercontent.com/32451366/74317016-e87bd580-4d7a-11ea-9b36-ba247d42a5f7.png)

**Comment by constantinpape** [comment]
Virtual cells still fail with the `NullPointerException`, however the tissue segmentation works now.

**Comment by tischi** [comment]
> The virtual cells should behave like segmentations in the platy-browser, so do they need the segmented tag in the filename?

@constantinpape 

1. to end up in the "prospr segmented" dropdown they need to have a name like, e.g, this: `prospr-6dpf-1-whole-segmented-allglands`, this is currently **not the case**.
1. to "behave" like segmentations they need to have `Type = "Segmentation"`, this is the case already.

**Comment by constantinpape** [comment]
> change the image file name to `prospr-6dpf-1-whole-segmented-virtual-cells` everything should work.

When we discussed this we agreed that the `segmented` in the name should not play a role and this should just depend on the  field `Type` in `images.json`. I think we should rather change this and not rename the virtual cell files.

**Comment by tischi** [comment]
Ok! I will change this.

But for `Modality` we still rely on the name, right?

**Comment by constantinpape** [comment]
> Ok! But for `Modality` we still use the file name, right?
> 
> That means the sorting into the different drop-downs will require both `Modality` and `Type`, right?
> 
> For example:
> 
> `prospr segmented` = `Modality` `Type`

Yes exactly. But both modalities `Mask` and `Segmentation` get mapped to dropdown `segmentation`. (We could also change that, but I think it will be too many dropdowns.)

**Comment by tischi** [comment]
Ok. done.
