### ISSUE TITLE
bookmarks

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/platybrowser-backend#6]
We have the following json definition for storing bookmark entries:
```
{"<name>": {"Layers": {"<layer-name>": {"Color": "<color-name>",
                                        "MinValue": <min-display-value>,
                                        "MaxValue": <max-display-value>,
                                        "SelectedIds": [<list of ids>],
                                        "ShowIn3d": <show this layer in 3d?>,
                                        "Tables": {"<table-name>": ["<column-name>", "<color-map>"]}},
                    "Position": [<position-coordinates>],
                    "View": [<affine-view-transformation>]}
```
Most of the fields are optional. I have added [bookmarks for the Figure 2 panels](https://github.com/platybrowser/platybrowser-backend/blob/master/data/0.6.6/misc/bookmarks.json).
Note that the `SelectedIds` in there are not yet up-to-date, I will fix this soon.
@tischer could you check that this format works for you? 

@HernandoMV @K-Meech @vzinche could you also have a look at this and see if you can fit your relevant panels into that format? Let me know if anything is unclear.

**Comment by tischi** [comment]
@constantinpape I realised even if there is no `Color` but only a `ColorMap` we do need brightness settings. Could you pleaser add them? I think `0 - 1000` was fine.

**Comment by constantinpape** [comment]
> @constantinpape I realised even if there is no `Color` but only a `ColorMap` we do need brightness settings. Could you pleaser add them? I think `0 - 1000` was fine.

Done. I feel like this relates to the `Modality` issue though, so let's discuss this on Monday as well.

**Comment by tischi** [comment]
@constantinpape I tried Figure 2C, looks like below. I don't think the selectedIds are at the same location as the view. Is that correct/ on purpose?

## View
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/2157566/74109504-4b574c00-4b84-11ea-907c-85814b06307d.png">

## SelectedIds
<img width="371" alt="image" src="https://user-images.githubusercontent.com/2157566/74109522-780b6380-4b84-11ea-9626-db14aa3e7066.png">

## LabelId within that view
One segment that is in the middle of that field of view has the number **5598**, which is not in above list.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/2157566/74109551-b30d9700-4b84-11ea-9574-a9f2c7e024a5.png">

**Comment by tischi** [comment]
> Note that the SelectedIds in there are not yet up-to-date, I will fix this soon.

Saw that too late :-)

**Comment by tischi** [comment]
@constantinpape `ShowIn3d` may not be precise enough, because one can see selected segments and/or whole images in 3D. 

1. I think we need two tags: `ShowSelectedImageSegmentsIn3D` and `ShowImageIn3D`
2. And I would like to renamed `SelectedIds` to `SelectedImageSegmentLabelIds`

**Comment by constantinpape** [comment]
@tischer
I made the updates you asked for now:
`SelectedIds` -> `SelectedLabelIds` (I decided against the full `SelectedSegmentLabelIds`, because `LabelIds` should be explicit enough).
We now have the option for `ShowSelectedSegmentsIn3d` and `ShowImageIn3d` and I replaced it in the bookmark file accordingly.

I didn't have time to look into updating the segment ids yet, will try to do this tomorrow.

**Comment by constantinpape** [comment]
@tischer
Kimberly added a new bookmark in 0f52fcdb9eb2d, that includes appending a table and then coloring the segmentation by a column in that table.
Appending the table works, but coloring does not work yet.

**Comment by vzinche** [comment]
@tischer 
I added new bookmarks and one of them [doesn't work](https://github.com/platybrowser/platybrowser-backend/pull/14#issuecomment-584660473).
Works in Python though.
Additionally 'SelectedLabelIds' doesn't seem to select anything.

**Comment by vzinche** [comment]
@tischi in 
`"Tables": {"<table-name>": ["<column-name>", "<color-map>"]`
 how do we refer to Glasbey 0 transparent?

**Comment by constantinpape** [comment]
There are several example bookmarks and I have found a couple of issues (also mentioned by others before in this thread). I will make a check-list so that it's easier to keep track of this for @tischer 

- [ ] `SelectedLabelIds` are not actually selected, see e.g. `"Figure 2C"`
- [ ] `ShowSelectedSegmentsIn3d`does not work yet, see e.g. `"Figure 2C"`
- [ ] Selecting columns for coloring does not work, see `"Figure 5C"`

@vzinche `"Figure 6B"` does not throw an error for me.

Side note:
I have fixed the ids for `"Figure 2C"`, but for `"Figure 2B"` and `"Figure 2D"` they are still out of date, I will fix this soon.

**Comment by vzinche** [comment]
"Figure 6B" works fine for me as well now, but the gene colors are completely messed up now (should be blue and green) for both 6a and 6b

**Comment by tischi** [comment]
> "Figure 6B" works fine for me as well now, but the gene colors are completely messed up now (should be blue and green) for both 6a and 6b

For me it works:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/2157566/74358865-7af39780-4dc2-11ea-9df6-dcadc7607961.png">

**Comment by tischi** [comment]
@constantinpape @vzinche 

Regarding the ColoringModel for the ColorByColumn. 

Maybe we could just use the exact same text as it is in the UI? Currently it is:

```java
	public static final String LINEAR_BLUE_WHITE_RED = "Linear - Blue White Red";
	public static final String LINEAR_BLUE_WHITE_RED_ZERO_TRANSPARENT = "Linear - Blue White Red (0 transparent)";
	public static final String LINEAR_VIRIDIS = "Linear - Viridis";
	public static final String CATEGORICAL_GLASBEY = "Categorical - Glasbey";
	public static final String CATEGORICAL_GLASBEY_ZERO_TRANSPARENT = "Categorical - Glasbey (0 transparent)";
```

It is a bit long, but it would be the easiest for me.

**Comment by vzinche** [comment]
I don't know what's wrong with me :D 

![Screenshot from 2020-02-12 18-10-46](https://user-images.githubusercontent.com/32451366/74359345-6368de80-4dc3-11ea-9b09-d2d19605114e.png)

**Comment by vzinche** [comment]
> Maybe we could just use the exact same text as it is in the UI? 

I am up for anything, as long as it's consistent

**Comment by tischi** [comment]
> I am up for anything, as long as it's consistent

Then let's decide whether we find the text in the UI **_very beautiful_** and then settle on it.
Is it beautiful or should we slightly change it?

**Comment by HernandoMV** [comment]
Hi all, sorry I've seen this now. Two questions,
- do you know how to scroll through all the mentions? (e.g. how do I see easily where my input is needed)
- for Figure 4 panels, @tischer could you provide a .json example so I can add the rest? It is unclear to me how to add the gene information.

**Comment by tischi** [comment]
@HernandoMV 

1. Nope, don't know how to scroll...
1. Here is the latest example for adding Bookmarks: https://github.com/platybrowser/platybrowser-backend/blob/master/data/0.6.6/misc/bookmarks.json

**Comment by constantinpape** [comment]
> > I am up for anything, as long as it's consistent
> 
> Then let's decide whether we find the text in the UI **_very beautiful_** and then settle on it.
> Is it beautiful or should we slightly change it?

I agree, we should settle on names for the color maps and use the same names in the bookmarks and in the UI.

Could we maybe remove the `Linear -` and `Categorical -` to make it more concise?

**Comment by vzinche** [comment]
@HernandoMV in two of my figure 6 bookmarks I am adding genes as well, you can check it [here](https://github.com/platybrowser/platybrowser-backend/blob/79589928357835b5ed3676bdf13861ae9fe4ef43/data/0.6.6/misc/bookmarks.json#L166)  

@constantinpape 
Not sure about removing `linear` and `categorical` from the UI though

**Comment by tischi** [comment]
@constantinpape 

GUI looks like this now:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/2157566/74591837-9d342200-501b-11ea-8fd3-39504763585a.png">

And the names for the bookmarks should be:

`BlueWhiteRed`
`BlueWhiteRedZeroTransparent`
`Glasbey`
`GlasbeyZeroTransparent`
`Viridis`
`ViridisZeroTransparent`

I feel we will need to change this in the near future to make it more general (i.e. add other things but zero), but I do not have the energy right now to pull this off. Thus, let's do it like this for now and suffer later.

**Comment by constantinpape** [comment]
> GUI looks like this now:

Looks good!

> Thus, let's do it like this for now and suffer later.

Ok :D.

**Comment by constantinpape** [comment]
The general bookmark functionality is working, I will open a separate issues for individual bookmarks that are not working.
