### ISSUE TITLE
s3 storage

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/platybrowser-backend#7]
@tischer
I have added a new version with xml files for the s3 data:
https://github.com/platybrowser/platybrowser-backend/tree/master/data/0.6.6

I have also uploaded most of the data to our s3 bucket now. Except for cilia segmentation, and raw data is still at lower resolution.

Could you check if this works in the platybrowser?

(I will rename it to 1.0.0 soon, but need to fix some more things with the tables before that.)

**Comment by tischi** [comment]
The `remote` storage location is missing from `images.json`, e.g.

```
Storage": {"local": "local/prospr-6dpf-1-whole-ache.xml"}
```

**Comment by constantinpape** [comment]
Should be fixed, could you try again?

**Comment by tischi** [comment]
works!

**Comment by constantinpape** [comment]
Still missing from s3:

- [ ] Raw data at full resolution
- [ ] Cilia segmentation

I will discuss this with Josep tomorrow.

**Comment by constantinpape** [comment]
I have uploaded the raw data at full scale now as well, but the fiji plugin does not load the higher scale levels for some reason. @tischi we should investigate once you are back.

**Comment by tischi** [comment]
> but the fiji plugin does not load the higher scale levels for some reason.

This is mysterious. Could you check this also with the local n5?

**Comment by constantinpape** [comment]
> This is mysterious. Could you check this also with the local n5?

Works fine in the local version.

**Comment by tischi** [comment]
Mein Verdacht ist: Du hast bei den ersten attributes.json vergessen ein Update zu machen, was die Anzahl der down-samplings angeht...

**Comment by constantinpape** [comment]
It was indeed an issue in the `attributes.json` metadata: the resolution in `setup0/timepoint0/attributes.json` was incorrect. Note that it was also incorrect in the local version, which worked fine.
So it seems like bdv handles this attribute different in the local/s3 case.
