### ISSUE TITLE
Many cells

### ISSUE THREAD

**Issue by tischi** [platybrowser/platybrowser-backend#9]
@constantinpape 
We have 33000 cells right now in the table.
Is this correct?

**Comment by constantinpape** [comment]
We have ~ 33,000 objects because cells are often still fragmented (and several objects are not cells).
There is a column `cells` which marks objects which (most likely) correspond to the actual cells.

**Comment by constantinpape** [comment]
@tischer closing this for now, feel free to reopen if you think there's more discussion necessary about this.
